packageExtensions:
  markdownlint-cli@*:
    dependencies:
      deep-extend: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: strict

yarnPath: .yarn/releases/yarn-3.2.0.cjs
