version: '3.8'

networks:
  development:
    driver: bridge

services:
  #########################
  ##      Backend        ##
  #########################

  dellingr:
    image: dellingr:latest
    build:
      args:
        PACKAGE: dellingr
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=3000
      - ENVIRONMENT=development
      - NODE_ENV=production
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - development
    container_name: dellingr

  #########################
  ##     Persistence     ##
  #########################

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=dellingr
      - POSTGRES_PASSWORD=masterkey
      - POSTGRES_USER=dellingr
    ports:
      - 5432:5432
    networks:
      - development
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./scripts/db:/docker-entrypoint-initdb.d
    container_name: dellingr-db
